language: go

go:
  - 1.13.x

env:
  - GO111MODULE=on

install: true

cache:
  directories:
    - $GOPATH/pkg/mod

jobs:
  include:
    - stage: "Compile"
      name: "Compile Packages and Dependencies"
      script: go build
    - stage: "Tests"
      name: "Unit Tests"
      script: go test ./... -coverprofile=coverage.txt -covermode=count
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: "Code Quality"
      name: "Code Quality Analysis"
      before_script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.21.0
      script: golangci-lint run
    - stage: "Release"
      name: "Release Binaries"
      script: skip
      deploy:
        - provider: script
          skip_cleanup: true
          script: curl -sL https://git.io/goreleaser | bash
          on:
            tags: true
            condition: $TRAVIS_OS_NAME = linux